
export default new Map([
["src/content/blog/arquitectura-backend-validacion-3d.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Farquitectura-backend-validacion-3d.mdx&astroContentModuleFlag=true")],
["src/content/blog/clean-architecture-3d.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fclean-architecture-3d.mdx&astroContentModuleFlag=true")],
["src/content/blog/validacion-3d-backend-csharp.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fvalidacion-3d-backend-csharp.mdx&astroContentModuleFlag=true")],
["src/content/blog/clean-architecture-dotnet-ia.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fclean-architecture-dotnet-ia.mdx&astroContentModuleFlag=true")],
["src/content/blog/concurrencia-optimista-3d.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fconcurrencia-optimista-3d.mdx&astroContentModuleFlag=true")],
["src/content/blog/arquitectura-agentes-ia-csharp.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Farquitectura-agentes-ia-csharp.mdx&astroContentModuleFlag=true")],
["src/content/casos/optimizacion-saas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasos%2Foptimizacion-saas.mdx&astroContentModuleFlag=true")],
["src/content/servicios/sistemas-criticos-dotnet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Fsistemas-criticos-dotnet.mdx&astroContentModuleFlag=true")],
["src/content/servicios/validacion-3d.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Fvalidacion-3d.mdx&astroContentModuleFlag=true")],
["src/content/servicios/auditoria-sistemas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Fauditoria-sistemas.mdx&astroContentModuleFlag=true")],
["src/content/servicios/arquitectura-ia-generativa.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Farquitectura-ia-generativa.mdx&astroContentModuleFlag=true")],
["src/content/casos/stealth-3d-ai.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasos%2Fstealth-3d-ai.mdx&astroContentModuleFlag=true")],
["src/content/servicios/renovacion-web.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Frenovacion-web.mdx&astroContentModuleFlag=true")],
["src/content/servicios/optimizacion-carga-3d.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Foptimizacion-carga-3d.mdx&astroContentModuleFlag=true")],
["src/content/servicios/arquitectura-ia-escalable.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservicios%2Farquitectura-ia-escalable.mdx&astroContentModuleFlag=true")]]);
		